model_name: mistralai/Mistral-7B-Instruct-v0.1
qlora:
  r: 8
  alpha: 16
  dropout: 0.05
  target_modules: [q_proj, k_proj, v_proj, o_proj]
training:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16
  num_train_epochs: 3
  lr: 2.0e-4
  max_length: 1024
  save_strategy: epoch
  logging_steps: 20

